### ISSUE TITLE
eduID: Epic Overview

### ISSUE THREAD

**Issue by dbrgn** [studentenportal/web#116]
See https://wiki.shibboleth.net/confluence/display/SHIB2/Integrating+Nginx+and+a+Shibboleth+SP+with+FastCGI

**Comment by dbrgn** [comment]
I still have the documents (SWITCHaai Federation Partner Agreement) here, but they're so old now that I will discard them.

If you decide to implement this feature, you should re-apply and fill out all documents. They need to be signed by the SWITCHaai Participant (VSHSR), a SWITCHaai member that recommends you (HSR or another participant) and SWITCH.

**Comment by saspeed** [comment]
The IT Helpdesk just ask about the current state of the application. (by sending me a scanned version of the very document you mentioned.) I think I can't do this on my own so would you dbrgn like to join me to implement it this semester?

**Comment by dbrgn** [comment]
The first step would probably be to either switch to Apache to be able to use the official Shibolleth client, or to compile a custom Nginx version with the https://github.com/nginx-shib/nginx-http-shibboleth module.

I'd probably lean towards the first approach, even though I like Nginx much much more than Apache.

If you want, @saspeed, you could do the Nginx -> Apache migration as the first step. This also requires the use of the [mod_xsendfile](https://tn123.org/mod_xsendfile/) module (which is supported natively in Nginx). This module is used to control the access to the document downloads. Once that's done, I could probably help with the implementation (although I don't really know how the integration with Shibolleth would look like in practice).

Also, don't forget this part:

> If you decide to implement this feature, you should re-apply and fill out all documents. They need to be signed by the SWITCHaai Participant (VSHSR), a SWITCHaai member that recommends you (HSR or another participant) and SWITCH.

**Comment by saspeed** [comment]
Having not much experience with python deployment on apache I'll consider this issue a major leap in hs16 which ill need to do a lot of research for.

**Comment by dbrgn** [comment]
Possibly @bananatreedad might be interested in a collaboration, he's currently studying in Biel. I told him about the Studentenportal yesterday.

A multi-site solution would require Shibboleth.

**Comment by dbrgn** [comment]
Regarding Python deployment on Apache I think [mod_wsgi](https://modwsgi.readthedocs.org/) is the way to go.

**Comment by fabianhauser** [comment]
@Murthy10 here the issue about the eduID-Login implementation. Note that this issue was originally created for SwitchAAI.

**Comment by Murthy10** [comment]
Answer of mail request at switch.ch:

> Guten Tag
>
>
>Um auf Ihrem Dienst das Login mit der SWITCH edu-ID einzuführen, müssten
>Sie einen Service Provider in der SWITCHaai Federation betreiben.
>
>
>Ihr Verein müsste Federation Partner werden. Weitere Informationen
>hierzu finden Sie hier:
>
>https://www.switch.ch/aai/join/partners/
>
>
>Technisch müsste Ihr Portal einen SAML2.0 Service Provider einbinden.
>Wir empfehlen und bieten Support für die Open Source Software Shibboleth:
>
>https://www.switch.ch/aai/guides/sp/
>
>https://www.switch.ch/aai/support/fedpartner-deployment/
>
>
>Die Nutzung anderer Implementierungen ist grundsätzlich schon möglich,
>allerding mit sehr eingeschränktem Support unsererseits. Auch sollten
>diese die grundlegenden Anforderungen, die in Higher Education
>Federations nötig sind, erfüllen:
>
>https://kantarainitiative.github.io/SAMLprofiles/fedinterop.html
>
>https://kantarainitiative.github.io/SAMLprofiles/saml2int.html
>
>(Shibboleth erfüllt diese Anforderungen von allen uns bekannten
>Implementierungen am Besten)
>
>
>Wenn Sie spezifische Features der SWITCH edu-ID nutzen möchten, die über
>die Funktionalitäten von SWITCHaai hinausgehen, könnten diese
>Informationen hilfreich sein:
>
>https://www.switch.ch/edu-id/services/
>
>
>Wir hoffen, diese Informationen ermöglichen Ihnen einen ersten Überblick
>über die Thematik.
>
>
>Freundliche Grüsse
>
>
>Thomas Bärecke

**Comment by dbrgn** [comment]
I think [this](https://github.com/studentenportal/web/issues/116#issuecomment-190279111) is still relevant.

**Comment by fabianhauser** [comment]
Hrm. I thought they had an easier integration than the whole SwitchAAi-Shibboleth-thing in the meantime...

**Comment by fabianhauser** [comment]
Steps to eduID Implementation:

Organisational part:

- [ ] Organise support by Ost Informatikdienste to be the "Sponsor" (See [Becomming a SwitchAAI Federation Partner](https://www.switch.ch/aai/join/partners/))
- [ ] Set up Paperwork (Contract)
  - [ ] Clearify responsible organisation (openhsr or own studentenportal association)


- [ ] Implement external auth support for django
- [ ] Plan and implement how to migrate existing users
- [ ] Setup webserver configuration
- [ ]  Setup Shibboleth-Daemon

**Comment by fabianhauser** [comment]
Current state: @Murthy10  has started with the setup, but the budget did not suffice to finish the implementation. Next steps: @openhsr/vorstand (@flObvious ) coordinates with gnice how to continue (or finds a volunteer who wants to implement it.)
